library(rbioapi)
library(Hmisc) # rcorr
library(igraph)
library(stringr)
library(matrixStats)
library(openxlsx)
library(RCy3)
library(tm)
library(randomForest)
library(ggplot2)
library(fpc)
library(SnowballC)